
<div class="alert alert-<?php echo $success === true ? 'success' : 'danger'; ?>">
<p><font color="blue"><?= isset($message['success']) ? $message['success'] : '' ?></font></p>
<p><font color="red"><?= isset($message['danger']) ? $message['danger'] : '' ?></font></p>
<p><font color="red"><?= isset($errors['pass_err']) ? $errors['pass_err'] : '' ?></font></p>
</div>


<?php echo $this->tag->linkTo(['/login', 'Go back', 'class' => 'btn btn-primary']); ?>