<div class="text-right">
    <a class="btn btn-outline-secondary" href="/my-orders" role="button">購入履歴</a>
    <a class="btn btn-outline-secondary" href="/cart" role="button">Cart</a>
    <a class="btn btn-outline-secondary" href="/logout" role="button">Logout</a>
</div>

<div class="h6" style="text-align: left"><font color="green"> こんにちは! <i class="fa-regular fa-face-smile"></i>
            <?php if ($this->session->has("user")): ?>
                <?= $this->session->get("user")["name"]; ?>さん</font>
            <?php endif; ?>
</div>
<div class="h6" style="text-align: right"><font color="green"> ショッピングカート <i class="fa-solid fa-cart-shopping"></i>は
            <?php if ($this->session->get("cart") >0): ?>
                <?= count($this->session->get("cart")) ?>件商品が入っています。</font>
                <?php else: ?>
                    空です。</font>
            <?php endif; ?>
</div>

<h1><?= $title ?></h1>

<form action="/index/search" method="POST">
            <div>
                <label for="category" size="25" maxlength="20">カテゴリー検索 : </label>
                <select name="category">
                    <option name="category" value="" >選択してください</option>
                    <?php foreach ($categories as $data): ?>
                        <?php if (empty($this->session->get('category')) === false): ?>
                            <option name="category" value="<?= $data->id ?>" <?= $data->id == $this->session->get('category') ? 'selected' : '' ?>><?= $data->nam ?></option>
                        <?php else: ?>
                            <option name="category" value="<?= $data->id ?>" ><?= $data->nam ?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            <div>
                <label for="color">花色 : </label>
                <?php foreach ($colors as $data): ?>
                    <?php if (empty($this->session->get('color')) === false): ?>
                        <?php foreach ($this->session->get('color') as $value): ?>
                            <?php $isFound = false; ?>
                            <?php if ($value == $data->colorId): ?>
                                <?php $isFound = true; ?>
                                <?php break; ?>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        <?php if ($isFound == true): ?>
                            <input type="checkbox" name="color[]" value="<?= $data->colorId ?>" <?= $data->colorId == $value ? 'checked' : ''?>><?= $data->colorName ?>
                            <?php else: ?>
                            <input type="checkbox" name="color[]" value="<?= $data->colorId ?>"><?= $data->colorName ?>
                        <?php endif; ?>
                    <?php else: ?>
                        <input type="checkbox" name="color[]" value="<?= $data->colorId ?>"><?= $data->colorName ?>
                    <?php endif; ?>
                <?php endforeach; ?>
                <br>
            </div>
            <div>
                <label for="stock">在庫 : </label>
                <select name="stock">
                    <option name="stock" value="">選択してください</option>
                <?php foreach ($stocks as $data): ?>
                    <?php if (empty($this->session->get('stock')) === false): ?>
                        <option name="stock" value="<?= $data->id ?>" <?= $data->id == $this->session->get('stock') ? 'selected' : '' ?>><?= $data->value ?></option>
                    <?php else: ?>
                        <option name="stock" value="<?= $data->id ?>"><?= $data->value ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
                </select>
                <label for="price">値段 : </label>
                <select name="price">
                    <option name="price" value="">選択してください</option>
                    <?php foreach ($prices as $data): ?>
                        <?php if (empty($this->session->get('price')) === false): ?>
                            <option name="price" value="<?= $data->id ?>" <?= $data->id == $this->session->get('price') ? 'selected' : '' ?>><?= $data->zone ?></option>
                        <?php else: ?>
                            <option name="price" value="<?= $data->id ?>"><?= $data->zone ?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            </div>
            <br>
                <input type="submit" class="btn btn-outline-secondary" value="検索する">
                <a class="btn btn-outline-secondary" href="/index/clear" role="button">クリア</a>
            </div>
        </form>
        <br>

<?php if ($flowers->count() > 0): ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Price</th>
            <th>Stock</th>
            <th>Cart</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Flowers quantity: <?= $flowers->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
                <?php foreach ($flowers as $flower): ?>
                    <tr>
                    <form method="POST" action="/cart">
                    <td><?= $flower->id; ?><input type="hidden" name="id" value="<?= $flower->id; ?>"></td>
                        <td><?= $flower->name; ?></td>
                        <td><?= $flower->price; ?></td>
                        <td><?= $flower->stock; ?></td>
                        <td>
                            <select name="quantity" id="quantity">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                            </select>
                            <input type="submit" value="カートに入れる" class="btn btn-primary">
                        </form>
                        </td>
                    </tr>
                <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
