
<h2><?= $title; ?></h2>
<hr>

<div class="container">
    <form action="/order/payment" method="post">
        <input type="hidden" name="orderId" value="<?= $data->id ?>">
        <h5>＜お届け先住所＞</h5>
        <div>氏名: <?= htmlspecialchars($data->name) ?></div>
        <div>郵送先：<p>〒<?= $data->postalCode ?> <?= $data->prefecture ?><?= htmlspecialchars($data->address); ?></p></div>
        <h5>＜購入商品＞</h5>
            <?php foreach ($details as $detail): ?>
                    <div class='row mt-2'>
                        <div class='col-3'>
                            <h6><?= $detail->flowerName ?> </h6>
                            <h7 class='text-danger'><?= $detail->flowerPrice ?>円</h7><br>
                            <h7>数量 : <?= $detail->quantity ?>
                        </div><br>
                    </div>
            <?php endforeach; ?>
        <br>
        <div class=h5 ><span style="text-decoration: underline">合計金額 : <?= number_format($data->totalPrice) ?> 円</span></div>
        <input type="hidden" name="totalPrice" value="<?= $data->totalPrice ?>">
        <input type="hidden" name="status" value="<?= $data->status ?>">
        <div>
            <input type="submit" value="注文確定（お支払い）">
        </div>
    </form>
    <br>
    <div>
        <a class="btn btn-outline-secondary" href="/cart.php" role="button">Cart へ戻る</a>
    </div>
    <br>
</div>
